ui:
  frameDelay: 5000000

  artwork:
    width: 500
    height: 500

  layout:
    pages: [nowPlaying, queue, search]
    cols: 2
    rows: 2

  theme: default

logging:
  logLevel: trace

settings:
  disableSigInt: true
  disableResize: false

mappings:
  - key: SPACE
    action: :playPauseToggle<CR>
  - key: r
    modifiers:
      - CTRL
    action: :restartSong<CR>
